version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
    container_name: netflix_app
    ports:
      - "8000:8000"
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_HOST_AUTH_METHOD=trust 
    container_name: netflix_db
    volumes:
      - .:/netflix_