# Generated by Django 4.1 on 2022-11-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollywood', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(),
        ),
    ]
