name: Hollywood API CD

on:
  push:
    branches: [master]

jobs:
  test:
    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_DB: uzmovi
          POSTGRES_USER: muxiddin87
          POSTGRES_PASSWORD: kamina87
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: moviesapi.muhiddin87.uz
            username: root
            key: {{secrets.KEY}}
            script:
              git pull
              systemctl restart gunicorn.service

